// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using beltexam.Models;

namespace beltexam.Migrations
{
    [DbContext(typeof(BeltExamContext))]
    [Migration("20180726145115_FirstMigrati")]
    partial class FirstMigrati
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("beltexam.Models.Like", b =>
                {
                    b.Property<int>("Likeid")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("postid");

                    b.Property<int?>("userid");

                    b.HasKey("Likeid");

                    b.HasIndex("postid");

                    b.HasIndex("userid");

                    b.ToTable("Like");
                });

            modelBuilder.Entity("beltexam.Models.Post", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("created_at");

                    b.Property<int?>("creatorid");

                    b.Property<string>("text")
                        .IsRequired();

                    b.Property<DateTime>("updated_at");

                    b.HasKey("id");

                    b.HasIndex("creatorid");

                    b.ToTable("Post");
                });

            modelBuilder.Entity("beltexam.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("confirm_password");

                    b.Property<string>("email")
                        .IsRequired();

                    b.Property<string>("firstname")
                        .IsRequired();

                    b.Property<string>("lastname")
                        .IsRequired();

                    b.Property<string>("password")
                        .IsRequired();

                    b.Property<string>("username")
                        .IsRequired();

                    b.HasKey("id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("beltexam.Models.Like", b =>
                {
                    b.HasOne("beltexam.Models.Post", "post")
                        .WithMany("likes")
                        .HasForeignKey("postid");

                    b.HasOne("beltexam.Models.User", "user")
                        .WithMany("likes")
                        .HasForeignKey("userid");
                });

            modelBuilder.Entity("beltexam.Models.Post", b =>
                {
                    b.HasOne("beltexam.Models.User", "creator")
                        .WithMany("posts")
                        .HasForeignKey("creatorid");
                });
#pragma warning restore 612, 618
        }
    }
}
